name: Publish Linux

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Minor version number'
        required: true
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: ubuntu-latest  # For a list of available runner types, refer to https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    permissions:
         contents: write

    env:
      Solution_Name: LaSSI.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Wap_Project_Directory: LaSSI    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: LaSSI/LaSSI.cspoj                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
      Publish_Script: LaSSI/publish.ps1

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Publish the file
      shell: pwsh
      working-directory: LaSSI
      run: |
        New-Item "output" -ItemType Directory
        #dotnet build -c Release LaSSI.csproj -p:BuildPlatform=Mac64 -p:MacBundleDotNet=true --output 'output/'
        dotnet publish -c Release LaSSI.csproj -p:PublishSingleFile=true --output 'output/'

    - name: Fix Linux file permission
      run: |
        pushd ${{ env.Wap_Project_Directory }}/output/
        chmod +x LaSSI
        zip LaSSI.linux_x64.v0.${{ github.event.inputs.version }}.zip LaSSI
        ls -al .
        popd
        mv ${{ env.Wap_Project_Directory }}/output/LaSSI.linux_x64.v0.${{ github.event.inputs.version }}.zip .
      shell: bash

    - name: Upload build artifact - Linux
      uses: ncipollo/release-action@main
      with:
        allowUpdates: true
        updateOnlyUnreleased: true
        artifactErrorsFailBuild: true
        draft: true
        prerelease: false
        commit: ${{ github.ref_name }}
        tag: 'v0.${{ github.event.inputs.version }}'
        artifacts: 'LaSSI.linux_x64.v0.${{ github.event.inputs.version }}.zip'
